// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPdW9jcXHwzFWvY86nGJORllpNDRn35zI',
    appId: '1:811572822581:web:ce6368941b219bcde3a77c',
    messagingSenderId: '811572822581',
    projectId: 'smartparkingsystem-f9fdd',
    authDomain: 'smartparkingsystem-f9fdd.firebaseapp.com',
    databaseURL: 'https://smartparkingsystem-f9fdd-default-rtdb.firebaseio.com',
    storageBucket: 'smartparkingsystem-f9fdd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp0-RihusVr3JxZGP3Ywu7g8sK2giFiVk',
    appId: '1:811572822581:android:21e715cff3594d74e3a77c',
    messagingSenderId: '811572822581',
    projectId: 'smartparkingsystem-f9fdd',
    databaseURL: 'https://smartparkingsystem-f9fdd-default-rtdb.firebaseio.com',
    storageBucket: 'smartparkingsystem-f9fdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVQegubFajHZJDQ1hFIa0R482G5xP7W8I',
    appId: '1:811572822581:ios:7da0788fdbc95d51e3a77c',
    messagingSenderId: '811572822581',
    projectId: 'smartparkingsystem-f9fdd',
    databaseURL: 'https://smartparkingsystem-f9fdd-default-rtdb.firebaseio.com',
    storageBucket: 'smartparkingsystem-f9fdd.firebasestorage.app',
    iosBundleId: 'com.example.datnVanVanh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVQegubFajHZJDQ1hFIa0R482G5xP7W8I',
    appId: '1:811572822581:ios:7da0788fdbc95d51e3a77c',
    messagingSenderId: '811572822581',
    projectId: 'smartparkingsystem-f9fdd',
    databaseURL: 'https://smartparkingsystem-f9fdd-default-rtdb.firebaseio.com',
    storageBucket: 'smartparkingsystem-f9fdd.firebasestorage.app',
    iosBundleId: 'com.example.datnVanVanh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPdW9jcXHwzFWvY86nGJORllpNDRn35zI',
    appId: '1:811572822581:web:a1c1d77c08ba9f74e3a77c',
    messagingSenderId: '811572822581',
    projectId: 'smartparkingsystem-f9fdd',
    authDomain: 'smartparkingsystem-f9fdd.firebaseapp.com',
    databaseURL: 'https://smartparkingsystem-f9fdd-default-rtdb.firebaseio.com',
    storageBucket: 'smartparkingsystem-f9fdd.firebasestorage.app',
  );

}