// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArsBq4BbNpkT35cm45lLZWt3QMH8cyon0',
    appId: '1:692296108761:web:82de3ac889687c012accc8',
    messagingSenderId: '692296108761',
    projectId: 'smartparking-bf0a0',
    authDomain: 'smartparking-bf0a0.firebaseapp.com',
    storageBucket: 'smartparking-bf0a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm3Z1lvVKgMXgZP4uTxFvxnVtCm0CfRYc',
    appId: '1:692296108761:android:709f43e225e4389f2accc8',
    messagingSenderId: '692296108761',
    projectId: 'smartparking-bf0a0',
    storageBucket: 'smartparking-bf0a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAABEWpWzzR-BgxKK0iTBHDZ7U7QkDwbQU',
    appId: '1:692296108761:ios:dae5009f5554f9f42accc8',
    messagingSenderId: '692296108761',
    projectId: 'smartparking-bf0a0',
    storageBucket: 'smartparking-bf0a0.firebasestorage.app',
    iosBundleId: 'com.example.datnVanVanh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAABEWpWzzR-BgxKK0iTBHDZ7U7QkDwbQU',
    appId: '1:692296108761:ios:dae5009f5554f9f42accc8',
    messagingSenderId: '692296108761',
    projectId: 'smartparking-bf0a0',
    storageBucket: 'smartparking-bf0a0.firebasestorage.app',
    iosBundleId: 'com.example.datnVanVanh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArsBq4BbNpkT35cm45lLZWt3QMH8cyon0',
    appId: '1:692296108761:web:1c19c809f8dd5a032accc8',
    messagingSenderId: '692296108761',
    projectId: 'smartparking-bf0a0',
    authDomain: 'smartparking-bf0a0.firebaseapp.com',
    storageBucket: 'smartparking-bf0a0.firebasestorage.app',
  );

}